# Generated by Django 2.2.3 on 2019-07-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='update_every',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
