# Generated by Django 2.2.3 on 2019-07-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bucketcontent_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('filepath', models.TextField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.ContentHistory')),
            ],
        ),
    ]
