# Generated by Django 2.2.3 on 2019-07-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contentfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bucketcontent',
            unique_together={('e_tag', 'name', 'bucket')},
        ),
    ]
