# Generated by Django 2.2.3 on 2019-07-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190718_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('file_created', 'File created'), ('file_updated', 'File updated'), ('file_deleted', 'File deleted'), ('file_empty', 'File empty')], max_length=30)),
                ('notification_status', models.CharField(choices=[('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled'), ('PROCESSED', 'Processed')], max_length=30)),
                ('bucket', models.ForeignKey(help_text='referencing to bucket to notify', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bucket')),
                ('bucket_file', models.ForeignKey(help_text='referencing to object to notify', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BucketContent')),
            ],
        ),
    ]
