# Generated by Django 2.2.3 on 2019-07-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='empty',
            field=models.BooleanField(default=False),
        ),
    ]
